# Test against this version of Node.js
environment:
  matrix:
    # node.js
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"

# Post-install test scripts.
test_script:
  - "npm run coveralls"
