# Test against this version of Node.js
environment:
  matrix:
    # node.js
    - nodejs_version: "0.12"
    - nodejs_version: "4.0"
    - nodejs_version: "4.1"
    - nodejs_version: "4.2"
    - nodejs_version: "4.3"
    - nodejs_version: "4.4"

# Post-install test scripts.
test_script:
  - "npm run coveralls"

# Don't actually build.
build: off
